# -*- coding: utf-8 -*-
"""Arrays.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/164uFwckAjtKT5ahuGZ4rprb2PdkzJ60X
"""

#pytohn array module
import array as myarray

#creating arrays
arr = myarray.array('i',[1,2,3])
arr1 = myarray.array('d',[1.0,2.1,2.4,2.5,2.6])
arr2 = myarray.array('u',['a','b','c','d'])

#typecodes
print(arr.typecode)
print(arr1.typecode)
print(arr2.typecode)

#looking at the arrays
print(arr)
print(arr1)
print(arr2)

#printing length of an array
print(len(arr))
print(len(arr1))
print(len(arr2))

#printing values in array
for i in range(0,len(arr)):
  print(arr[i], end=" ")
print("\n")
for i in range(0,len(arr1)):
  print(arr1[i], end=" ")
print("\n")
for i in range(0,len(arr2)):
  print(arr2[i], end=" ")

#making a list of array and printing in loop
x = list(range(1,100))
new_array = myarray.array('i',x)
for i in range(0,len(new_array)):
  print(new_array[i],end=" ")
print("\n")

print (new_array[25])
print("\n")
#adding new elements in array
new_arr = myarray.array('i',[3,4,5,6,7,8,9,10])
for i in range(0,len(new_arr)):
  print(new_arr[i],end=" ")
print(end="\n")

#using insert and indexing to add new values
new_arr.insert(0,2)
new_arr.insert(0,1)
for i in range(0,len(new_arr)):
  print(new_arr[i],end=" ")
print("\n")

#using append to add values on last
new_arr.append(11)
for i in range(0,len(new_arr)):
  print(new_arr[i],end=" ")

#update element in array
old_array = myarray.array('i',[1,2,3,4,5])

for i in range(0,len(old_array)):
  print(old_array[i], end=" ")
print("\n")

old_array[3] = 8
for i in range(0,len(old_array)):
  print(old_array[i], end=" ")
print("\n")

#deleting element in array
old_array.pop(4)
for i in range(0,len(old_array)):
  print(old_array[i], end=" ")

#slicing operation in arrays
x = list(range(0,100,2))
akisha = myarray.array('i',x)
for i in range (0,len(akisha)):
  print(akisha[i],end = " ")
print("\n")

#slicing the array
aku = akisha[5:10]
for i in range (0,len(aku)):
  print(aku[i],end = " ")
print("\n")

#[10:-20] #slicing the array from index 10 to index -20
aki = akisha[10:-20] #slicing the array from index 10 to index -20
for i in range (0,len(aki)):
  print(aki[i],end = " ")
print("\n")

#reverse list
rev_array = akisha[::-1]
for i in range (0,len(rev_array)):
  print(rev_array[i],end = " ")
print("\n")

#searching operation in array using index
x = list(range (0,100))
array = myarray.array('i',x)
for i in range (0,len(array)):
  print(array[i],end = " ")
print("\n")

index = array.index(77)
res = array[index]
print(index,res)
print("\n")

#sorting arrays
sorted_array = myarray.array('i',[5,6,7,82,3,4])
sort_array = sorted_array.tolist()
sort_array.sort()
print(sort_array)

sort_array.sort(reverse = True)
print(sort_array)

#creating arrays by numpy
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print("\n")

zeros = np.zeros((2,2))
ones = np.ones((2,2))
const = np.full((2,2),5)
iden = np.eye(2)
random = np.random.random((2,2))
print(zeros)
print("\n")
print(ones)
print("\n")
print(const)
print("\n")
print(iden)
print("\n")
print(random)
print("\n")

#1-D
zero1 = np.array(1)
print(zero1)
print("\n")
one1 = np.array([1,1])
print(one1)
print("\n")
#2-D
two1 = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(two1)
print("\n")
#3-D
multi = np.array([1,2,3,4,5], ndmin = 5)
print(multi)

#reading from numpy arrays
simple_array = np.array([1,2,3,4,5,6,7,8,9])
for i in range(0,len(simple_array)):
  print(i,end = " ")
print("\n")

#update values
simple_array[8] = 100
print(simple_array)
print("\n")

#deleting element
simple_array = np.delete((simple_array),4)
print(simple_array)

#searching for element
res = np.where(simple_array == 4)
print(res)

#checking index
print(simple_array[3])









